version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
  build:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: 'Restoring dependencies'
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    steps:
      - run:
          name: 'Running test'
          command: npm run test:unit
  publish:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: 'Publishing in Docker Hub: mariehmai/lyrichords'
          command: TAG=0.1.0-web-$CIRCLE_BUILD_NUM && docker build -t mariehmai/lyrichords:$TAG . && docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push mariehmai/lyrichords:$TAG

workflows:
  version: 2
  build-test-publish:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
